build:
  image: fdplugins/remote-build:0.5.9
  commands:
    - ruby ~/remote_build.rb
    - framgia-ci report
    - framgia-ci finish

  environment:
    - USER_NAME=test01
    - KEY_CHAIN_PASS=Aa@123456
    - REMOTE_IP=10.0.1.119
    - BUILD_BRANCH=master
    - BUILD_LANE=beta
# deploy:
#   ssh-mac:
#     image: fdplugins/remote-build:0.3.1
#     host: 192.168.5.21
#     user: tran.vuong.minh
#     keychain: Minh1209
#     swiftlint: true
#     oclint: false
#     fastlane: beta
