build:
  image: fdplugins/remote-build:0.5.3
  commands:
    - ruby ~/remote_build.rb
    - framgia-ci report

  environment:
    - USER_NAME=ci
    - USER_PASSWORD=123456
    - KEY_CHAIN_PASS=123456
    - REMOTE_IP=192.168.5.12
    - FASTLANE=beta

# deploy:
#   ssh-mac:
#     image: fdplugins/remote-build:0.3.1
#     host: 192.168.5.21
#     user: tran.vuong.minh
#     keychain: Minh1209
#     swiftlint: true
#     oclint: false
#     fastlane: beta
