build:
  image: fdplugins/remote-build:0.6.3
  commands:
    - printenv
    - ruby ~/remote_build.rb
    - framgia-ci report
    - framgia-ci finish

  environment:
    # config remote build machine and user
    - SSH_KEY=$$SSH_KEY
    - USER_NAME=$$USER_NAME
    - KEY_CHAIN=$$KEY_CHAIN
    - KEY_CHAIN_PASS=$$KEY_CHAIN_PASS
    - REMOTE_IP=$$REMOTE_IP
    # config beta build. When push event to branch
    - BUILD_BRANCH=master
    - BUILD_LANE=beta
# deploy:
#   ssh-mac:
#     image: fdplugins/remote-build:0.3.1
#     host: 192.168.5.21
#     user: tran.vuong.minh
#     keychain: Minh1209
#     swiftlint: true
#     oclint: false
#     fastlane: beta
