build:
  image: ubuntu
  commands:
    - echo start

deploy:
  ssh:
    host:
     - 192.168.5.21
    user: tran.vuong.minh
    port: 22
    commands:
      - export DRONE_REPO=DRONE_REPO 
      - echo DRONE_REPO
