build:
  image: fdplugins/remote-build:0.5.7
  commands:
    - ruby ~/remote_build.rb
    - framgia-ci report
    - framgia-ci finish

  environment:
    - USER_NAME=tran.vuong.minh
    - KEY_CHAIN_PASS=Minh1209
    - REMOTE_IP=192.168.5.12
    - FASTLANE=beta
    - FRAMGIA-CI=test

# deploy:
#   ssh-mac:
#     image: fdplugins/remote-build:0.3.1
#     host: 192.168.5.21
#     user: tran.vuong.minh
#     keychain: Minh1209
#     swiftlint: true
#     oclint: false
#     fastlane: beta
