project_type: android
test:
  build:
    ignore: true
    command: fastlane build
  checksytle:
    ignore: true
    command: fastlane lint

  # test:
  #   ignore: false
  #   command: fastlane test
