environment:
  - REMOTE_IP=10.0.1.119
  - USER_NAME=test04
  - KEY_CHAIN=login
  - KEY_CHAIN_PASS=Aa@123456
  - SSH_KEY=  -----BEGIN RSA PRIVATE KEY-----
              MIIJKAIBAAKCAgEAufX4inyUJojSoiWbLOUgLu6dPQE1PG8IKLqdB4x0QFF1ywNH
              VrCfNc6DRvuXxS4cLFYo6l7vPJh/bE10Ibx8MFv2UNSUnb87jQDPWdSrR3ANqpkF
              BrF7CtdEkYVZeADOdXCJIdc0pVEpec5krlC/HLgCGYUiILs7vLKPtzTrlIb7YlIt
              RPzL5H/RQPQpYV0cWp3lT9MI9poiSvyRc63vu4ooFRewiSq5n8RpStWFqMO4WL0E
              E10D+scp44y15w1uLAlHa8CCigDDZaA7adMP6S2rlDytT9TtuOV8g8keaBHkko+8
              1Gv2nd1pJgURC2V28ME23BrS7k3ar17fVcTsSerXTlr7OwclZoW6vCUYj4F2bocN
              AXlLdyWYcnn5lK/7Tv5Shy7H4HemiNa9RsndxnEIxr/IFAh/u9+/eAYWKlX4QXbr
              jl+NBTVqe7n0LQsQWh32O8UuTLAEUQ4u9h0SaeeB3iJE4qTjtSoJoSZui7r5oRZw
              v1dNmYjCX6ztoAWD5VqpLXW3pNCIYq99F/EdMfAGwcHZH53bwiCAF7QS9iQzCq+P
              zBK4jqg4zPf3O9UWP3JKcCU6/+bJFV3wyVrmoeTCYqMyZoXH/06W+76CWVO2fO9u
              00sCetRomiN6xCjzpCop1qiYxcQkj7TugYx0p9fdCL9UolIccdKVzJE6K6ECAwEA
              AQKCAgBqoJk0fx5LwiRUiQ+i/HYpsvRB6JFn55pcEDS+AVEfGBZco7KiCIAh0BoB
              930cuMW6vmSTjn/K1P4rUXYHahYjfHeN/XaBxQcWYKKENadIPP35FeiF3/pXSvus
              HTQh1QSM3kwjNUyghhssFqYwNWh/xRqfG3FoJzOnjRNOz29NKOC3jbsbVYBrssZ/
              YgDgLQ13ABZeYPlAvTxwlsWn+NH/TMaS4ZR98huhenONT0VmcWMgrrDJkYoYn15r
              dWFP7KmBYoirRiUTkEB54xhuI3F6GI/LXcdagRMV87AjuIxQzAGt7/EsNAOinTQP
              ctRFHpbGkWMtbcwIjGeaKuIQQevhsjF2d4WzjipKriKHQex3rkagfvUBko+6qMyY
              YJMJXlTMF38VedT78KIMxzX9UHkG08SGhXiIUiqQlRdU3a1ctnJalkNjNmZ75jJA
              CHTRE0UIP0wjSZfwHpAWThdTYN7scQNJPQjtonIKszGkWThSGiK2izy8YCBGjEEJ
              VBuV29UK2X2jJlWMMdtBsozwqqdWT2825BG5f10ZAmouNkxdJzkKBSe/HIZpRfR5
              CyDebTptJM3ZPUFIsNbkV/fFqmk84qMMeKzTEPXqS+LqHazDBjFV2ZEhYEujd+9T
              4iWf/z+zYBNTAY1xV8TqN18gX1Ufx/Bk2THwVQYA7dul8WUJyQKCAQEA91Ilu7DL
              0Dlmoggc80uWYwe/Trgi8go1EPQ2BORsP1v14cmmxVksqsCFA/cjNXRG1KgYlY8Y
              FbtrnxR89fjq8opVzomGvSTwOuYk2K2E3zUM3++t9BdiRT3tmKgWhFJNHSv/zW/k
              W+q+npNGgTmKpJB+fwa47SLog6FivtGy+CoVt2q6kgZhGeasOzYI3jwhlgMyk51i
              Lj7ImV7++wOLgSGsSTIpYNS8CJLh4stJF1X/1zxVUJifHCgMgeyWBc9UvUIH2Ga5
              CfMptcVbQZSVvwyomEhauLNhFdn7wL48OXllPV0ZDH4CVjtV5QYUbadErO6OnJrV
              Yd76w8V73lSNAwKCAQEAwHyVhSSsF4frEUrYK9I4sCLNNiQrf7YgADyDwznZuBIf
              RXhC2J90QYrJNrHHmCEglbEzuxOLSsc83dit4lUs8QNWu3w/dRsEVnwRQ9xUpkbH
              alTaUqshXP+pfYb48BWnpKMNZ05tpXmMRmiVE7p6s3zYijrmGp6fOOEhaPkZyXcI
              NHupWUV5PIc6kD7Otkie8g72EVuZIbATDQAXsqATq+VBlOkLbajCgLUd8pCV32Kg
              665ZGlmNiQATEoP96FSF9S9Kwec+J8WpQzfo4x+1XQQ3pZin1y0pjWELWSzQRzl7
              YXBGKshMgIxbpBuocL8WUMRX3yB31IZKfdAHzEmJiwKCAQEAvZf71SZzF+zpAM23
              Y8tOPhxyS6ZdI68vfw+3WYjCcs/MbopnjmIOG9f6IFAUbaX1ppA2SHCpxf8nQYwz
              P1zSv5vMq8hBwj3O61gCZxieA35noEPc1oIWk34l5iD1Ifr1oqdYMeTU6qHJ/0Zn
              hijWX9FlJ3u/yAo6tK3DRQT8bcHVZAYtgEPjrDdpUPrbUYJHPPi2jPLZkRoQLYLl
              dQgCqbtml7Ycgl6Sxv/Sqkmsfncu6ZEW1fIqByusau0zFMEb9Pnpibs1nqsKDo58
              pomBQjQyCottAKqCgn3YwKkVAfpN4fy8dxciM3jJIAjJIEZaHzfBm8wWSDDni6yY
              iJfIgQKCAQBhIz4Nd+lE4rmU+3FGBAvJj3aCGRS+mXlixSc1cU9XHgYb98m8KhPw
              M4rBiEwSkL0x7cAOa5mCvjMQPZXav2MzqZyudtBLV7wDrQ7FcT5ivxtJpNKcn3Hx
              za+KAoBEIJl+cy6DcMfSlxlcOtDoqNXdGGbqsziGPIBbovlKUVNbIS/J1JIs0+uP
              ySqbuqZ0xQc5XqV9Mv1/S60BhYdwBGqI9+P1svmqeFzXuQ8I50BLACn3Zf/fVUwg
              1CHL2UJcabNEfX47hmgOiCiYHHHxlIHhFAzFC9m/tDHhABVLBluBZhfGn3M5ieVZ
              hfuFQNPrOfOYBM3XczolzTNwdHhK9t1rAoIBAD2V7xdkqci7b3GYDQcBT6FTEhHd
              LxDiqVDsYUu0JZz8L8jseGy66rKFb7XfAwJnqO9z47/vjr5NQYKwjIdYTozAOxvb
              TOFkqyKJhGr81b4VbNxPcjRSbe/9XF1mlL307w579ZOKgxxvxyCyoF362IDU2s1m
              UK6JPgsKV3+GWqiezyU/nZF0wYOuAdtGoceNuUQjIqwM9PduQNowwBpfN70ClBDE
              unnyPkpxIJ6V5rR6t+t/156pgj8MVBX/hswSw4LHSXZVk3UZ3OzRA6rABtEuJPcn
              wGsWXuV5enN1HA6H6+s33mUUR9GU7QvROxyElYexL5d7P1owhlQ5KWtLaok=
              -----END RSA PRIVATE KEY-----
